# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5a2b22b87f4142c90b72ba2a0d9605b22a44ba086118703338ee9b900cf2c8a8a9a52f6342fc3cefe731aba66db15047adc908263df2936c017b6d303272969f

test:
  secret_key_base: 2fdfa3e28b7d84553a33a41b24b03fe39a468bb642126b448963dbdff10cea17c46732f74b6bae4c89e95538cbaaed9b81cfe48308cec3a49476c1c146531d71

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
